# Generated by Django 2.1.7 on 2019-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locmet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
        migrations.AlterField(
            model_name='tmax',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tmax',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
    ]
