# Generated by Django 2.1.7 on 2019-03-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locmet', '0006_auto_20190305_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rainfall',
        ),
        migrations.DeleteModel(
            name='Tmax',
        ),
        migrations.DeleteModel(
            name='Tmin',
        ),
    ]
